name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  hooks_riverpod:
  riverpod_annotation:
  sqflite:
  shared_preferences:
  sqflite_common_ffi:
  path_provider:
  path:
  flutter_localization:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  riverpod_generator:

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
